name: fiat
services:
  webapp:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      secrets:
        - github_token
    command: /bin/bash -c "./docker-entrypoint.sh dotnet DfE.FindInformationAcademiesTrusts.dll"
    develop:
      watch: 
        - path: ..
          action: rebuild
    ports:
      - "80:8080/tcp"
    env_file:
      - .env
secrets:
  github_token:
    environment: GITHUB_TOKEN
