<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Dfe.AcademiesApi.Client" Version="1.0.15" />
      <PackageReference Include="GovUK.Dfe.PersonsApi.Client" Version="0.1.5" />
    </ItemGroup>

</Project>
