<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="GovUK.Dfe.PersonsApi.Client" Version="0.1.4" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.22">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.22" />
        <PackageReference Include="GovUK.Dfe.CoreLibs.Contracts" Version="1.0.98" />
        <PackageReference Include="GovUK.Dfe.CoreLibs.http" Version="1.0.10" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\DfE.FindInformationAcademiesTrusts.Data\DfE.FindInformationAcademiesTrusts.Data.csproj" />
    </ItemGroup>

</Project>
