name: .NET

on:
  pull_request:
    branches: [ main, '**-feature' ]
    paths:
      - '**.cs'
      - '**.cshtml'
      - '**.sql'
      - '**.csproj'
      - '**.sln'
      - '**/appsettings*json'
      - '.config/dotnet-tools.json'
      - 'stryker-config.json'
  workflow_dispatch:

env:
  DOTNET_VERSION: 8.0.x
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-24.04
    steps:
    - name: Check out code
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

    - name: Setup .NET
      uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install other dotnet tools (including stryker, code coverage and entity framework cli)
      run: dotnet tool restore

    - name: Add nuget package source
      run: dotnet nuget add source --username USERNAME --password $GH_TOKEN --store-password-in-clear-text --name github "https://nuget.pkg.github.com/DFE-Digital/index.json"

    - name: Build solution
      run: |
        dotnet restore DfE.FindInformationAcademiesTrusts
        dotnet build DfE.FindInformationAcademiesTrusts -c Release

    - name: Ensure there are no pending migrations
      run: dotnet ef migrations has-pending-model-changes --context FiatDbContext --project DfE.FindInformationAcademiesTrusts.Data.FiatDb --startup-project DfE.FindInformationAcademiesTrusts

    - name: Run mutation tests
      run: dotnet stryker --reporter "markdown" --reporter "html" --output "${{ github.workspace }}"

    - name: Print stryker report
      if: ${{ !cancelled() }}
      run: |
        # Construct the full path to the markdown file
        REPORT_FILE="${{ github.workspace }}/reports/mutation-report.md"

        # Check if the file exists
        if [ -f "$REPORT_FILE" ]; then
          echo "File exists: $REPORT_FILE"
          # Print the report as a Step Summary
          echo "$(cat $REPORT_FILE)" >> $GITHUB_STEP_SUMMARY
        else
          echo "::error ::File not found: $REPORT_FILE"
        fi

    - name: Upload Stryker report
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      if: ${{ !cancelled() }}
      with:
        name: stryker-report
        path: ${{ github.workspace }}/reports/mutation-report.html
